main: main09.o
	g++ -o main.exe main09.o -std=c++2a
main09.o: main09.cpp
	g++ -c main09.cpp -std=c++2a
all: main09.o
	g++ -o main.exe main09.o -std=c++2a
clean:
	@echo "Cleaning main09..."
	del -include *.o, *.exe